config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: redirect('/ideas')

  resources :ideas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/idea.rb
class Idea < ApplicationRecord
  mount_uploader :picture, PictureUploader 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :set_idea, only: %i[ show edit update destroy ]

  # GET /ideas or /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1 or /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas or /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to idea_url(@idea), notice: "Idea was successfully created." }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1 or /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to idea_url(@idea), notice: "Idea was successfully updated." }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1 or /ideas/1.json
  def destroy
    @idea.destroy

    respond_to do |format|
      format.html { redirect_to ideas_url, notice: "Idea was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def idea_params
      params.require(:idea).permit(:title, :description, :picture, :published_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= form_with(model: idea) do |form| %>
  <% if idea.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
        <% idea.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-4">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="my-4">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="my-4">
    <%= form.label :picture, class: "form-label" %>
    <%= form.file_field :picture, class: "form-control" %>
  </div>

  <div class="my-4">
    <%= form.label :published_at, class: "form-label" %>
    <%= form.date_field :published_at, class: "form-control" %>
  </div>

  <div class="my-4">
    <%= form.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/ideas/_idea.html.erb
<div id="<%= dom_id idea %>" class="row">
  <div class="col-md-6 my-3">
    <%= image_tag(idea.picture_url, width: '100%') if idea.picture.present? %>
  </div>

  <div class="col-md-6 my-3">
    <h1>
      <%= idea.title %>
    </h1>
  <time class="badge rounded-pill bg-info text-dark">
    <%= idea.published_at %>
  </time>

    <p class="my-4">
      <%= idea.description %>
    </p>
  </div>

</div>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render "form", idea: @idea %>

<br>

<div>
  <%= link_to "Show this idea", @idea %> |
  <%= link_to "Back to ideas", ideas_path %>
</div>

app/views/ideas/index.html.erb
<h1>Ideas</h1>

<div id="ideas">
  <% @ideas.in_groups_of(3, false) do |idea_group| %>

  <div class="row">
    <% idea_group.each do |idea| %>
      <div class="col-md-4 my-3">
        <%= link_to idea do %>
        <%= image_tag(idea.picture_url(:thumb), width: '100%') if idea.picture.present? %> 
      <% end %>
        <p>
        </p>
      </div>
    <% end %>
  </div>
  <% end %>
</div>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render "form", idea: @idea %>

<br>

<div>
  <%= link_to "Back to ideas", ideas_path %>
</div>

app/views/ideas/show.html.erb
<%= render @idea %>

<% if user_signed_in? %>

<div class="btn-toolbar">
  <%= link_to "Edit this idea", edit_idea_path(@idea), class: "btn btn-info" %> 
  <%= button_to "Destroy this idea", @idea, method: :delete, class: "btn btn-danger ms-3" %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>Pdiary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column h-100">
    <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Pdiary</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/ideas">Ideas</a>
        </li>
        <li class="nav-item">
        <%= link_to "New idea", new_idea_path, class: "nav-link active" %>
        </li>
      </ul>

      <ul class="nav">
      <li class="nav-item">
      <% if current_user.present? %>
        <%= current_user.email %>
      <% end %>
      </li>
      </ul>
      <span class="navbar-text pull-right">
      <% if user_signed_in? %>
      <%= button_to "Logout", destroy_user_session_path, method: :delete, data: {turbo: false}, class: "btn btn-link" %>
      <% else %>
      <%= link_to "Login", new_user_session_path, class: "btn btn-link" %>
      <% end %>
      </span>

    </div>
  </div>
</nav>

<div class="container">

  <p class="text-success"><%= notice %></p>
  <p class="text-danger"><%= alert %></p>

    <%= yield %>
    </div>
    <footer class="footer mt-auto py-3 bg-light">
    <div class="container">
    <span class="text-muted">Pdiary 製作委員会</footer>
    </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>